spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/VeneUsers
    username: root
    password: toor
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  servlet:
    context-path: /uaa
  port: 8081