spring:
  datasource:
    url: jdbc:mysql://localhost:33006/VeneUsers?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: toor
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    #generate-ddl: true
    show-sql: true

server:
  servlet:
    context-path: /uaa
  port: 8081