db_info:
  schema: ${DB_USERS_SCHEMA:users}
  user: ${DB_USERS_USERNAME:root}
  password: ${DB_USERS_PASSWORD:toor}

spring:
  datasource:
    url: jdbc:mysql://localhost:33006/${db_info.schema}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${db_info.user}
    password: ${db_info.password}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true

server:
  servlet:
    context-path: /uaa
  port: 8081