package org.venexer.questionmakerserver.repos.access

import org.venexer.questionmakerserver.models.access.AccessGroupToQuestion

interface AccessGroupToQuestionRepo : AccessToQuestionRepo<AccessGroupToQuestion>