package org.venexer.questionmakerserver.repos.access

import org.venexer.questionmakerserver.models.access.AccessOrganizationToQuestion

interface AccessOrganizationToQuestionRepo : AccessToQuestionRepo<AccessOrganizationToQuestion>